---
title: "students"
output: html_notebook
---

```{r setup}
library(tidyverse)
```

```{r build}
last_name <- c("Bartelt", "Butt", "Cable", "Dupont", "Kim", "Lee", "Llanga", "Lu.h", "Lu.j", "Palmucci", "Rosales", "Schmidt", "Shoben", "Smith", "Song", "Strain", "Strouse", "Sweeney", "Trimarco", "Willard")

vignette <- c("How do I convert a long dataframe into a wide one?",
              "How do I filter my data for certain rows?",
              "How do I make a new column in my dataframe?",
              "How do I filter my data for specific columns?",
              "How do I calculate summaries for each of my columns?",
              "How do I count the number of observations in my data?",
              "How do I group my data by certain values?",
              "How do I sort my data?",
              "How do I separate one column into two?",
              "How do I merge two columns?",
              "How do I merge two datasets?",
              "How do I import data into R?",
              "How do I export data from R to Excel?",
              "How do I add rows or columns to my dataframe?",
              "How do I rename a column in R?",
              "How do I make a new dataframe in R?",
              "How do I set or change the type of graph in R?",
              "How do I change the axis labels?",
              "How do I change the theme of my graph?",
              "How do I save my graph as an image?")

funs <- c("pivot_wider", 
          "filter", 
          "mutate", 
          "select", 
          "summarize", 
          "count", 
          "group_by", 
          "arrange", 
          "separate()", 
          "unite", 
          "x_join()", 
          "read_x (csv, tsv, etc)", 
          "write_x (csv, tsv, etc) ", 
          "bind_rows/cols", 
          "rename()", 
          "tibble()", 
          "geom_point", 
          "labs+", 
          "theme_x()", 
          "ggsave()")

students <- tibble(name = last_name, title = vignette, fun = funs)
```

