#intro to functions
```{r}
do_this(to_that)

do_this(to_that, using_these)

data$entry_name

entries <- data$entry_name

chromosome$id

ids <- chromosome$id


```


#intro to the pipe
```{r}
go(eat(put_on(wakeup(self), "clothes"), "brekfast"), to = "work")
   

wakeup(self) %>% 
  put_on("clothes") %>% 
  eat("breakfast") %>% 
  go(to = "work")
  

wakeup(self) %>% 
  put_on("clothes") %>% 
  eat("breakfast") %>% 
  fmk() %>% 
  go(to = "work")


morning_routine <- wakeup(self) %>% 
  put_on("clothes") %>% 
  eat("breakfast") %>% 
  fmk() %>% 
  go(to = "work")

#data %>% 
#  select("gene", "expression_level_control", "expression_level_experimental") %>% 
#  mutate(differential_expression_level = expression_level_experimental - expression_level_control) %>% 
#  arrange(desc(differential_expression_level))

#ranked_dge <- data %>% 
#  select("gene", "expression_level_control", "expression_level_experimental") %>% 
#  mutate(differential_expression_level = expression_level_experimental - expression_level_control) %>% 
#  arrange(desc(differential_expression_level))


chromosome %>% 
  select("id", "variations", "basepairs") %>% 
  mutate(percent_var = variations/basepairs) %>% 
  arrange(desc(percent_var))


chromosome_var <- chromosome %>% 
  select("id", "variations", "basepairs") %>% 
  mutate(percent_var = variations/basepairs) %>% 
  arrange(desc(percent_var))
```

